blog/urls.py
from django.conf.urls import url
from . import views


app_name = 'blog'
urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^post/(?P<pk>[0-9]+)/$',views.detail,name='detail')
]

comments/urls.py
from django.conf.urls import url
from . import views


app_name = 'comments'
urlpatterns = [
    url(r'^comment/post/(?P<post_pk>[0-9]+)/$',views.post_comment,name='post_comment'),
]

pyblog/urls.py
from django.contrib import admin
from django.conf.urls import url,include

urlpatterns = [
    url('admin/', admin.site.urls),
    url(r'',include('blog.urls')),
    url(r'',include('comments.urls')),

]

blog/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=100) #分类名

class Tag(models.Model):
    name = models.CharField(max_length=100) #标签名

class Post(models.Model):
    title = models.CharField(max_length=70) #标题
    body = models.TextField() #正文
    created_time = models.DateTimeField() #创建时间
    modified_time = models.DateTimeField() #最后一次修改时间
    excerpt = models.CharField(max_length=200,blank=True) #摘要
    category = models.ForeignKey(Category,on_delete=models.CASCADE) #一对多关系 一个分类可以有多篇文章
    tags = models.ManyToManyField(Tag,blank=True) #多对多关系 一篇文章可以有多个标签 一个标签也可以有多篇文章
    author = models.ForeignKey(User,on_delete=models.CASCADE) #作者 User是django已经写好的用户模型 规定一篇文章只能有一个作者

    def get_absolute_url(self):
        return reverse('blog:detail',kwargs={'pk':self.pk})

    def get_index_url(self):
        return reverse('blog:index')

comments/models.py
from django.db import models

# Create your models here.

class Comment(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=255)
    url = models.URLField(blank=True)
    text = models.TextField()
    created_time = models.DateTimeField(auto_now_add=True)

    post = models.ForeignKey('blog.Post',on_delete=models.CASCADE)

    def __str__(self):
        return self.text[:20]

comments/forms.py
from django import forms
from .models import Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name','email','url','text']

blog/views.py
import markdown
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.http import HttpResponse
from django.shortcuts import render,get_object_or_404
from blog.models import Post
import markdown
# Create your views here.
from comments.forms import CommentForm


def index(request):
    post_list = Post.objects.all().order_by('-created_time')
    paginator = Paginator(post_list, 3)
    page = request.GET.get('page')
    try:
        contacts = paginator.page(page)
    except PageNotAnInteger:
        contacts = paginator.page(1)
    except EmptyPage:
        contacts = paginator.page(paginator.num_pages)
    return render(request,'blog/index.html',context={
        'post_list':post_list,
        'contacts':contacts,
    })

def detail(request,pk):
    body = get_object_or_404(Post,pk=pk)
    body.body = markdown.markdown(body.body,['extra','codehilite','toc'])
    form = CommentForm()
    comment_list = body.comment_set.all()
    context = {'body':body,
               'form':form,
               'comment_list':comment_list}
    return render(request,'blog/detail.html',context=context)

comments/views.py
from django.shortcuts import render, get_object_or_404, redirect
from blog.models import Post
from comments.forms import CommentForm

# Create your views here.

def post_comment(request,post_pk):
    post = get_object_or_404(Post,pk=post_pk)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.save()
            return redirect(post)
        else:
            comment_list = post.comment_set.all()
            context = {'post':post,
                       'form':form,
                       'comment_list':comment_list
                       }
            return render(request,'blog/detail.html',context=context)
    return redirect(post)


blog/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <title>Martin</title>

    <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- css -->
    <link rel="stylesheet" href="{% static '/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="{% static '/css/pace.css' %}">
    <link rel="stylesheet" href="{% static '/css/custom.css' %}">
    <link rel="stylesheet" href="{% static '/css/highlights/github.css' %}">

    <!-- js -->
    <script src="{% static '/js/jquery-2.1.3.min.js' %}"></script>
    <script src="{% static '/js/bootstrap.min.js' %}"></script>
    <script src="{% static '/js/pace.min.js' %}"></script>
    <script src="{% static '/js/modernizr.custom.js' %}"></script>
    <script src="{% static '/js/script.js' %}"></script>

</head>

<body>
<div class="container">
    <header id="site-header">
        <div class="row">
            <div class="col-md-4 col-sm-5 col-xs-8">
                <div class="logo">
                    <h1><a href="{% url 'blog:index' %}"><b>Mar</b>tin</a></h1>
                </div>
            </div><!-- col-md-4 -->
            <div class="col-md-8 col-sm-7 col-xs-4">
                <nav class="main-nav" role="navigation">
                    <div class="navbar-header">
                        <button type="button" id="trigger-overlay" class="navbar-toggle">
                            <span class="ion-navicon"></span>
                        </button>
                    </div>
                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav navbar-right">
                            <li class="cl-effect-11"><a href="{% url 'blog:index' %}" data-hover="首页">首页</a></li>
                            <li class="cl-effect-11"><a href="full-width.html" data-hover="博客">博客</a></li>
                            <li class="cl-effect-11"><a href="about.html" data-hover="关于">关于</a></li>
                            <li class="cl-effect-11"><a href="contact.html" data-hover="联系">联系</a></li>
                        </ul>
                    </div><!-- /.navbar-collapse -->

                </nav>
                <div id="header-search-box">
                    <a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
                    <div id="search-form" class="search-form">
                        <form role="search" method="get" id="searchform" action="#">
                            <input type="search" placeholder="搜索" required>
                            <button type="submit"><span class="ion-ios-search-strong"></span></button>
                        </form>
                    </div>
                </div>
            </div><!-- col-md-8 -->
        </div>
    </header>
</div>
<div class="copyrights">Collect from <a href="http://www.cssmoban.com/">网页模板</a></div>
<div class="copyrights">Modified by <a href="http://zmrenwu.com/">gz的博客</a></div>

<div class="content-body">
    <div class="container">
        <div class="row">
            <main class="col-md-8">
                {% block main %}
                {% endblock main %}
            </main>
            <aside class="col-md-4">
                {% block toc %}
                {% endblock toc %}
                <div class="widget widget-recent-posts">
                    <h3 class="widget-title">最新文章</h3>
                    {% for post in contacts %}
                    <ul>
                        <li>
                            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                        </li>
                    </ul>
                    {% endfor %}
                </div>

                <div class="widget widget-archives">
                    <h3 class="widget-title">归档</h3>
                    <ul>
                        <li>
                            <a href="#">2017 年 5 月</a>
                        </li>
                        <li>
                            <a href="#">2017 年 4 月</a>
                        </li>
                        <li>
                            <a href="#">2017 年 3 月</a>
                        </li>
                    </ul>
                </div>

                <div class="widget widget-category">
                    <h3 class="widget-title">分类</h3>
                    <ul>
                        <li>
                            <a href="#">Django 博客教程 <span class="post-count">(13)</span></a>
                        </li>
                        <li>
                            <a href="#">Python 教程 <span class="post-count">(11)</span></a>
                        </li>
                        <li>
                            <a href="#">Django 用户认证 <span class="post-count">(8)</span></a>
                        </li>
                    </ul>
                </div>

                <div class="widget widget-tag-cloud">
                    <h3 class="widget-title">标签云</h3>
                    <ul>
                        <li>
                            <a href="#">Django</a>
                        </li>
                        <li>
                            <a href="#">Python</a>
                        </li>
                        <li>
                            <a href="#">Java</a>
                        </li>
                        <li>
                            <a href="#">笔记</a>
                        </li>
                        <li>
                            <a href="#">文档</a>
                        </li>
                        <li>
                            <a href="#">AngularJS</a>
                        </li>
                        <li>
                            <a href="#">CSS</a>
                        </li>
                        <li>
                            <a href="#">JavaScript</a>
                        </li>
                        <li>
                            <a href="#">Snippet</a>
                        </li>
                        <li>
                            <a href="#">jQuery</a>
                        </li>
                    </ul>
                </div>
                <div class="rss">
                    <a href=""><span class="ion-social-rss-outline"></span> RSS 订阅</a>
                </div>
            </aside>
        </div>
    </div>
</div>


<footer id="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p class="copyright"><a href="http://www.cssmoban.com/"
                                                        target="_blank" title="title">blog</a>
                    - 由<a href="http://zmrenwu.com/" title="网页模板" target="_blank">gz</a>修改
                </p>
            </div>
        </div>
    </div>
</footer>

<!-- Mobile Menu -->
<div class="overlay overlay-hugeinc">
    <button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
    <nav>
        <ul>
            <li><a href="index.html">首页</a></li>
            <li><a href="full-width.html">博客</a></li>
            <li><a href="about.html">关于</a></li>
            <li><a href="contact.html">联系</a></li>
        </ul>
    </nav>
</div>


</body>
</html>

blog/templates/blog/about.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
    <head>
        <title>Black &amp; White</title>

       <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- css -->
    <link rel="stylesheet" href="{% static '/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="{% static '/css/pace.css' %}">
    <link rel="stylesheet" href="{% static '/css/custom.css' %}">

    <!-- js -->
    <script src="{% static '/js/jquery-2.1.3.min.js' %}"></script>
    <script src="{% static '/js/bootstrap.min.js' %}"></script>
    <script src="{% static '/js/pace.min.js' %}"></script>
    <script src="{% static '/js/modernizr.custom.js' %}"></script>
    </head>

    <body id="page">
        <div class="container">
            <header id="site-header">
                <div class="row">
                    <div class="col-md-4 col-sm-5 col-xs-8">
                        <div class="logo">
                            <h1><a href="index.html"><b>Black</b> &amp; White</a></h1>
                        </div>
                    </div><!-- col-md-4 -->
                    <div class="col-md-8 col-sm-7 col-xs-4">
                        <nav class="main-nav" role="navigation">
                            <div class="navbar-header">
                                <button type="button" id="trigger-overlay" class="navbar-toggle">
                                    <span class="ion-navicon"></span>
                                </button>
                            </div>

                            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                                <ul class="nav navbar-nav navbar-right">
                                    <li class="cl-effect-11"><a href="index.html" data-hover="Home">Home</a></li>
                                    <li class="cl-effect-11"><a href="full-width.html" data-hover="Blog">Blog</a></li>
                                    <li class="cl-effect-11"><a href="about.html" data-hover="About">About</a></li>
                                    <li class="cl-effect-11"><a href="contact.html" data-hover="Contact">Contact</a></li>
                                </ul>
                            </div><!-- /.navbar-collapse -->
                        </nav>
                        <div id="header-search-box">
                            <a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
                            <div id="search-form" class="search-form">
                                <form role="search" method="get" id="searchform" action="#">
                                    <input type="search" placeholder="Search" required>
                                    <button type="submit"><span class="ion-ios-search-strong"></span></button>
                                </form>
                            </div>
                        </div>
                    </div><!-- col-md-8 -->
                </div>
            </header>
        </div>

        <div class="content-body">
            <div class="container">
                <div class="row">
                    <main class="col-md-12">
                        <h1 class="page-title">About Me</h1>
                        <article class="post">
                            <div class="entry-content clearfix">
                                <figure class="img-responsive-center">
                                    <img class="img-responsive" src="img/me.jpg" alt="Developer Image">
                                </figure>
                                <p>Responsive web design offers us a way forward, finally allowing us to design for the ebb and flow of things. There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don’t look even slightly.</p>
                                <p>Responsive web design offers us a way forward, finally allowing us to design for the ebb and flow of things. There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don’t look even slightly.</p>
                                <div class="height-40px"></div>
                                <h2 class="title text-center">Social</h2>
                                <ul class="social">
                                    <li class="facebook"><a href="#"><span class="ion-social-facebook"></span></a></li>
                                    <li class="twitter"><a href="#"><span class="ion-social-twitter"></span></a></li>
                                    <li class="google-plus"><a href="#"><span class="ion-social-googleplus"></span></a></li>
                                    <li class="tumblr"><a href="#"><span class="ion-social-tumblr"></span></a></li>
                                </ul>
                            </div>
                        </article>
                    </main>
                </div>
            </div>
        </div>
        <footer id="site-footer">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <p class="copyright">&copy; 2014 ThemeWagon.com</p>
                    </div>
                </div>
            </div>
        </footer>

        <!-- Mobile Menu -->
        <div class="overlay overlay-hugeinc">
            <button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
            <nav>
                <ul>
                    <li><a href="index.html">Home</a></li>
                    <li><a href="full-width.html">Blog</a></li>
                    <li><a href="about.html">About</a></li>
                    <li><a href="contact.html">Contact</a></li>
                </ul>
            </nav>
        </div>

        <script src="js/script.js"></script>

    </body>
</html>

blog/templates/blog/contact.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
    <head>
        <title>Black &amp; White</title>

        <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- css -->
    <link rel="stylesheet" href="{% static '/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="{% static '/css/pace.css' %}">
    <link rel="stylesheet" href="{% static '/css/custom.css' %}">

    <!-- js -->
    <script src="{% static '/js/jquery-2.1.3.min.js' %}"></script>
    <script src="{% static '/js/bootstrap.min.js' %}"></script>
    <script src="{% static '/js/pace.min.js' %}"></script>
    <script src="{% static '/js/modernizr.custom.js' %}"></script>
    </head>

    <body id="page">
        <div class="container">
            <header id="site-header">
                <div class="row">
                    <div class="col-md-4 col-sm-5 col-xs-8">
                        <div class="logo">
                            <h1><a href="index.html"><b>Black</b> &amp; White</a></h1>
                        </div>
                    </div><!-- col-md-4 -->
                    <div class="col-md-8 col-sm-7 col-xs-4">
                        <nav class="main-nav" role="navigation">
                            <div class="navbar-header">
                                <button type="button" id="trigger-overlay" class="navbar-toggle">
                                    <span class="ion-navicon"></span>
                                </button>
                            </div>

                            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                                <ul class="nav navbar-nav navbar-right">
                                    <li class="cl-effect-11"><a href="index.html" data-hover="Home">Home</a></li>
                                    <li class="cl-effect-11"><a href="full-width.html" data-hover="Blog">Blog</a></li>
                                    <li class="cl-effect-11"><a href="about.html" data-hover="About">About</a></li>
                                    <li class="cl-effect-11"><a href="contact.html" data-hover="Contact">Contact</a></li>
                                </ul>
                            </div><!-- /.navbar-collapse -->
                        </nav>
                        <div id="header-search-box">
                            <a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
                            <div id="search-form" class="search-form">
                                <form role="search" method="get" id="searchform" action="#">
                                    <input type="search" placeholder="Search" required>
                                    <button type="submit"><span class="ion-ios-search-strong"></span></button>
                                </form>
                            </div>
                        </div>
                    </div><!-- col-md-8 -->
                </div>
            </header>
        </div>

        <div class="content-body">
            <div class="container">
                <div class="row">
                    <main class="col-md-12">
                        <h1 class="page-title">Contact</h1>
                        <article class="post">
                            <div class="entry-content clearfix">
                                <form action="#" method="post" class="contact-form">
                                    <div class="row">
                                        <div class="col-md-6 col-md-offset-3">
                                            <input type="text" name="name" placeholder="Name" required>
                                            <input type="email" name="email" placeholder="Email" required>
                                            <input type="text" name="subject" placeholder="Subject" required>
                                            <textarea name="message" rows="7" placeholder="Your Message" required></textarea>
                                            <button class="btn-send btn-5 btn-5b ion-ios-paperplane"><span>Drop Me a Line</span></button>
                                        </div>
                                    </div>	<!-- row -->
                                </form>
                            </div>
                        </article>
                    </main>
                </div>
            </div>
        </div>
        <footer id="site-footer">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <p class="copyright">&copy; 2014 ThemeWagon.com</p>
                    </div>
                </div>
            </div>
        </footer>

        <!-- Mobile Menu -->
        <div class="overlay overlay-hugeinc">
            <button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
            <nav>
                <ul>
                    <li><a href="index.html">Home</a></li>
                    <li><a href="full-width.html">Blog</a></li>
                    <li><a href="about.html">About</a></li>
                    <li><a href="contact.html">Contact</a></li>
                </ul>
            </nav>
        </div>

        <script src="js/script.js"></script>

    </body>
</html>

blog/templates/blog/detail.html
{% extends 'base.html' %}
{% load staticfiles %}
        {% block main%}
            <article class="post post-{{ body.pk }}">
                <header class="entry-header">
                    <h1 class="entry-title">{{ body.title }}</h1>
                    <div class="entry-meta">
                        <span class="post-category"><a href="#">{{ body.category.name }}</a></span>
                        <span class="post-date"><a href="#"><time class="entry-date" datetime="{{ body.created_time }}">{{ body.created_time }}</time></a></span>
                        <span class="post-author"><a href="#">{{ body.author }}</a></span>
                        <span class="comments-link"><a href="#">4 评论</a></span>
                        <span class="views-count"><a href="#">588 阅读</a></span>
                    </div>
                </header>
                <div class="entry-content clearfix">
                    {{ body.body|safe }}
                </div>
            </article>

            <section class="comment-area" id="comment-area">
                <hr>
                <h3>发表评论</h3>
                <form action="{% url 'comments:post_comment' body.pk %}" method="post" class="comment-form">
                    <div class="row">
                        <div class="col-md-4">
                            <label for="{{ form.name.id_for_label }}">名字:</label>
                            {{ form.name }}
                            {{ form.name.errors }}
                        </div>
                        <div class="col-md-4">
                            <label for="{{ form.email.id_for_label }}">邮箱:</label>
                            {{ form.email }}
                            {{ form.email.errors }}
                        </div>
                        <div class="col-md-4">
                            <label for="{{ form.url.id_for_label }}">URL:</label>
                            {{ form.url }}
                            {{ form.url.errors }}
                        </div>
                        <div class="col-md-12">
                            <label for="{{ form.text.id_for_label }}">评论:</label>
                            {{ form.text }}
                            {{ form.text.errors }}
                        <button type="submit" class="comment-btn">发表</button>
                        </div>
                    </div>
                </form>
                <div class="comment-list-panel">
                    <h3>评论列表，共 <span>4</span> 条评论</h3>
                    <ul class="comment-list list-unstyled">
                        {% for comment in comment_list %}
                        <li class="comment-item">
                        <span class="nickname">{{ comment.name }}</span>
                        <time class="submit-date">{{ comment.created_time }}</time>
                        <div class="text">
                            {{ comment.text }}
                        </div>
                        </li>
                            {% empty %}
                            暂无评论
                        {% endfor %}
                    </ul>
                </div>
            </section>
        {% endblock main %}

        {% block toc %}
            <div class="widget widget-content">
                <h3 class="widget-title">文章目录</h3>
                <ul>
                    <li>
                        <a href="#">教程特点</a>
                    </li>
                    <li>
                        <a href="#">谁适合这个教程</a>
                    </li>
                    <li>
                        <a href="#">在线预览</a>
                    </li>
                    <li>
                        <a href="#">资源列表</a>
                    </li>
                    <li>
                        <a href="#">获取帮助</a>
                    </li>
                </ul>
            </div>
        {% endblock toc %}

blog/templates/blog/index.html
{% extends 'base.html' %}
        {% block main %}
            {% for post in contacts %}
            <article class="post post-{{ post.pk }}">
                <header class="entry-header">
                    <h1 class="entry-title">
                        <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                    </h1>
                    <div class="entry-meta">
                        <span class="post-category"><a href="#">{{ post.category.name }}</a></span>
                        <span class="post-date"><a href="#"><time class="entry-date"
                                                                  datetime="{{ post.created_time }}">{{ post.created_time }}</time></a></span>
                        <span class="post-author"><a href="#">{{ post.author }}</a></span>
                        <span class="comments-link"><a href="#">4 评论</a></span>
                        <span class="views-count"><a href="#">588 阅读</a></span>
                    </div>
                </header>
                <div class="entry-content clearfix">
                    <p>{{ post.excerpt }}</p>
                    <div class="read-more cl-effect-14">
                        <a href="{{ post.get_absolute_url }}" class="more-link">继续阅读 <span class="meta-nav">→</span></a>
                    </div>
                </div>

                {% empty %}
                    <div class="no-post">暂时没有文章发布！</div>
            </article>
            {% endfor %}

            <!-- 简单分页效果
            <div class="pagination-simple">
                <a href="#">上一页</a>
                <span class="current">第 6 页 / 共 11 页</span>
                <a href="#">下一页</a>
            </div>
            -->
{#            <div class="pagination">#}
{#                <ul>#}
{#                    <li><a href="">1</a></li>#}
{#                    <li><a href="">...</a></li>#}
{#                    <li><a href="">4</a></li>#}
{#                    <li><a href="">5</a></li>#}
{#                    <li class="current"><a href="">6</a></li>#}
{#                    <li><a href="">7</a></li>#}
{#                    <li><a href="">8</a></li>#}
{#                    <li><a href="">...</a></li>#}
{#                    <li><a href="">11</a></li>#}
{#                </ul>#}
{#            </div>#}

         <!-- 列表分页器 -->
            <nav aria-label="Page navigation" style="margin-left: 40%">
          <ul class="pagination">
            <li>
                {% if contacts.has_previous %}
              <a href="?page={{ contacts.previous_page_number }}" aria-label="Previous">
                {% endif %}
                <span aria-hidden="true">&laquo;

                </span>
              </a>
            </li>

                {% for pg in contacts.paginator.page_range %}
                        {% if contacts.number == pg %}
                            <li><a href="?page={{ pg }}">{{ pg }}</a></li>
                        {% else %}
                            <li><a href="?page={{ pg }}">{{ pg }}</a></li>
                        {% endif %}
                {% endfor %}

            <li>
                {% if contacts.has_next %}
              <a href="?page={{ contacts.next_page_number }}" aria-label="Next">
                {% endif %}
                <span aria-hidden="true">&raquo;
                </span>
              </a>
            </li>
          </ul>
        </nav>

        {% endblock main %}